# Define the workflow's name
name: CI Pipeline for Portfolio Website

# Specify the event that triggers the workflow
on:
  push:
    branches:
      - main  # Trigger the workflow on push events to the main branch

# Define the job that will run in the workflow
jobs:
  validate-and-check:
    # Specify the runner environment for the job
    runs-on: ubuntu-latest
    
    # Define the steps to be executed in the job
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4  # Use the official checkout action to access the repository code

      # Validate HTML files using the html-validate action
      - name: Validate HTML
        uses: chafik/html-validate-action@v1  # Use a pre-built action for HTML validation
        with:
          files: "./**/*.html"  # Specify the pattern for HTML files to validate
          recursive: true  # Enable recursive search for HTML files

      # Check for broken links using the lycheeverse/lychee-action
      - name: Check for broken links
        uses: lycheeverse/lychee-action@v1.9.3  # Use a pre-built action for link checking
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Provide a GitHub token for link checking
        with:
          args: --verbose --no-progress *.html  # Specify arguments for link checking
          fail: true  # Fail the workflow if broken links are found
