name: CI Pipeline for Portfolio Website

# This workflow will run on every push to the main branch
on:
  push:
    branches:
      - main

# Define the job that will run in the workflow
jobs:
  build-and-validate:
    # Run the job on the latest Ubuntu runner
    runs-on: ubuntu-latest

    # Steps to be executed in the job
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4
        # This action checks out your repository under $GITHUB_WORKSPACE, 
        # so your workflow can access it.

      # Validate HTML files using the html5validator action
      - name: Validate HTML
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        # This action uses the html5validator Python package to validate 
        # HTML files according to the W3C standards.
        with:
          root: './'
          files: 'index.html'

      # Check for broken links using the Lychee action
      - name: Check for broken links
        uses: lycheeverse/lychee-action@v1.8.0
        # This action uses Lychee, a fast and simple link checker, to 
        # scan your files for broken links.
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          LYCHEE_CONFIG: ./
        # You can customize Lychee's behavior by creating a 
        # .lychee.toml file in your repository root.
